remote_theme: ddc-java/ddc-day-book
repository_link:
  enabled: false
page_navigator:
  enabled: true
titles_from_headings:
  enabled: false
prev_next_navigation:
- bottom

title: "NASA APoD"
description: "NASA Astronomy Photo of the Day"
author:
  name: "Nick Bennett"

# Do not change the following line.
  copyright: true
